### ISSUE TITLE
Obtain pictures of rooms and buildings

### ISSUE THREAD

**Issue by Vanessa-Salgado** [Vanessa-Salgado/UCSB-Hacks#5]
User Story: User can see a list of Buildings

Breakdown: Get 5 images first and put into Parse database 

- [x] check the UCSB website 
- [x] physically take pictures
- [x] save it into the Parse database

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/142711413-5b28465d-6009-49ab-92ee-8c7886091e47.png)

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/142711509-795f9ccf-43df-465e-ac33-1ae37e778df8.png)

**Comment by miguel-luis9** [comment]
<img width="686" alt="Screen Shot 2021-11-19 at 6 40 26 PM" src="https://user-images.githubusercontent.com/90986902/142711846-ac7e684f-a453-4f61-a49a-c24b5da2b51e.png">

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/142711892-0ae2fb68-7589-47a5-b26a-dc378918ec06.png)

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/142711933-b2b09671-5339-4270-b8b6-3eb96d86928a.png)

**Comment by miguel-luis9** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=95bf548289&attid=0.1&permmsgid=msg-f:1716998130584822130&th=17d400b3e584a172&view=att&disp=safe

**Comment by miguel-luis9** [comment]
![IMG_1869](https://user-images.githubusercontent.com/90986902/142745477-8bb39b51-6be5-432e-a3cb-8f4924e74df5.JPG)

**Comment by miguel-luis9** [comment]
![IMG_1872](https://user-images.githubusercontent.com/90986902/142745714-512cbfa3-8212-4a28-b76d-76c7f3088b82.jpg)

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/142745886-fcaf57c9-21f1-4768-838b-cd10774ce8d0.png)
