### ISSUE TITLE
Obtain an Icon Image

### ISSUE THREAD

**Issue by Vanessa-Salgado** [Vanessa-Salgado/UCSB-Hacks#7]
User Story: Can see icon image

- [x] Find an image without a watermark
- [x] Resize to an image icon size
- [x] upload images to the Image folder on Github

**Comment by dylancocoletzi** [comment]
![study-desk-icon-website-design-desktop-envelopment-development-premium-pack-study-desk-vector-flat-color-icon-167309034](https://user-images.githubusercontent.com/86747062/141656597-0a7b49db-6a40-4bc6-b2f7-6cad7b6790b5.jpg)

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/141656738-5e3e3331-daf1-4a80-858f-eac295c59214.png)

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/141656747-6ad36892-62dc-4264-b09c-cee6d21f332a.png)

**Comment by miguel-luis9** [comment]
![image](https://user-images.githubusercontent.com/90986902/141656793-8eced3de-6138-455c-880e-4b29330ab487.png)
